github:
  user_or_org: nsls-ii-forge
channels:
  sources:
    - nsls2forge
    - defaults
  targets:
    - [nsls2forge, main]
compiler_stack: comp7
azure:
  user_or_org: leofang
  project_name: nsls2ptycho
provider:
  linux: azure
  osx: azure
  win: azure
upload_on_branch: master
