# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    demands:
    - gpu -equals true
    name: BNL-machines
  strategy:
    matrix:
      linux_cuda_compiler_version10.0python3.6:
        CONFIG: linux_cuda_compiler_version10.0python3.6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:10.0
      linux_cuda_compiler_version10.0python3.7:
        CONFIG: linux_cuda_compiler_version10.0python3.7
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:10.0
      linux_cuda_compiler_version10.0python3.8:
        CONFIG: linux_cuda_compiler_version10.0python3.8
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:10.0
      linux_cuda_compiler_version10.1python3.6:
        CONFIG: linux_cuda_compiler_version10.1python3.6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:10.1
      linux_cuda_compiler_version10.1python3.7:
        CONFIG: linux_cuda_compiler_version10.1python3.7
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:10.1
      linux_cuda_compiler_version10.1python3.8:
        CONFIG: linux_cuda_compiler_version10.1python3.8
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:10.1
      linux_cuda_compiler_version10.2python3.6:
        CONFIG: linux_cuda_compiler_version10.2python3.6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:10.2
      linux_cuda_compiler_version10.2python3.7:
        CONFIG: linux_cuda_compiler_version10.2python3.7
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:10.2
      linux_cuda_compiler_version10.2python3.8:
        CONFIG: linux_cuda_compiler_version10.2python3.8
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:10.2
      linux_cuda_compiler_version9.2python3.6:
        CONFIG: linux_cuda_compiler_version9.2python3.6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:9.2
      linux_cuda_compiler_version9.2python3.7:
        CONFIG: linux_cuda_compiler_version9.2python3.7
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:9.2
      linux_cuda_compiler_version9.2python3.8:
        CONFIG: linux_cuda_compiler_version9.2python3.8
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:9.2
    maxParallel: 1
  timeoutInMinutes: 360
  workspace:
    clean: all

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export UPLOAD_ON_BRANCH="master"
        export CONDA_FORGE_DOCKER_RUN_ARGS="-t --rm"
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)